### ISSUE TITLE
[Bug] TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by Kristinita** [CodeEffect/BoundKeys#11]
### 1. Summary

I can not begin to use BoundKeys, I get stack trace.

### 2. Expected behavior

![BoundKeys](https://github.com/CodeEffect/BoundKeys/raw/master/BoundKeys.png)

### 3. Actual behavior

```python
command: bound_keys
Error parsing JSON: Expecting property name enclosed in double quotes: line 373 column 13 (char 11616)
Error parsing JSON: Expecting property name enclosed in double quotes: line 7 column 2 (char 126)
Error parsing JSON: Expecting property name enclosed in double quotes: line 8 column 11 (char 211)
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "boundkeys in E:\Sublime Text 3\Data\Installed Packages\BoundKeys.sublime-package", line 356, in run
TypeError: 'bool' object is not iterable
```

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install BoundKeys via Package Control → I restart Sublime Text → <kbd>Ctrl+Shift+P</kbd> → `List bound keys` → I get stack trace.

All my `.sublime-keymap` files successfully worked for me.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by mg979** [comment]
Possible fix, insert at line 43:

            # other trailing commas
            fixTrailing = re.compile("%s\s+%s" % (
                re.escape(','),
                re.escape("}")
            ), re.MULTILINE)
            data = re.sub(fixTrailing, "}", data)

**Comment by Kristinita** [comment]
@mg979 ,  I paste it right?

```python
            # Build 3021 & 3033 have trailing commas in the default files
            fixTrailing = re.compile("%s\s+%s" % (
                re.escape("},"),
                re.escape("]")
            ), re.MULTILINE)
            data = re.sub(fixTrailing, "}   ]", data)

            # other trailing commas
            fixTrailing = re.compile("%s\s+%s" % (
                re.escape(','),
                re.escape("}")
            ), re.MULTILINE)
            data = re.sub(fixTrailing, "}", data)

            return json.loads(data, strict=False)
```

It doesn't work for me, I get the same error.

Thanks.

**Comment by mg979** [comment]
In my installation it works. I also had to do [this](https://github.com/CodeEffect/BoundKeys/issues/6).
Maybe you have something else yet that causes an error. What does the console say exactly?
