### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by hgrimelid** [CodeEffect/BoundKeys#6]
I'm getting this error message in console when trying to run "List Bound Keys".

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./boundkeys.py", line 375, in run
  File "./boundkeys.py", line 99, in getOutput
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 7: ordinal not in range(128)
```

**Comment by mjl** [comment]
Fix, line 336:

```
 jsonObj = self.jsonify(open(filePath, "r", encoding='UTF8').read())
```

Add an encoding parameter to open, like so:

```
 jsonObj = self.jsonify(open(filePath, "r", encoding='UTF8').read())
```
